server:
  port: 9001

spring:
  application:
    name: myshop-user
  datasource:
    url: jdbc:mysql://192.168.222.134:3307/springcloud1?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka
  instance:
    prefer-ip-address: true
